name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  test:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    environment: CI
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "pypy-3.8"]
        runs-on: [ubuntu-latest]

        include:
          - python-version: "3.8"
            runs-on: windows-latest

          - python-version: "3.10"
            runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: pip install -e .[test]

      - name: Run unit tests
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_REPORTER_ID}}
        with:
          coverageCommand: pytest --cov-report=xml

  # dist:
  #   name: Distribution build
  #   runs-on: ubuntu-latest
  #   needs: [pre-commit]

  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: Build sdist and wheel
  #       run: pipx run build

  #     - uses: actions/upload-artifact@v2
  #       with:
  #         path: dist

  #     - name: Check products
  #       run: pipx run twine check dist/*

  #     - uses: pypa/gh-action-pypi-publish@v1.4.2
  #       if: github.event_name == 'release' && github.event.action == 'published'
  #       with:
  #         user: __token__
  #         # Remember to generate this and set it in "GitHub Secrets"
  #         password: ${{ secrets.pypi_password }}
  #         # Remove this line
  #         repository_url: https://test.pypi.org/legacy/
